# Golang CircleCI 2.0 configuration file
version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11 #

    working_directory: /go/src/github.com/parkmenow/PMN-api

    environment: # environment variables for primary container
          GO111MODULE: "on"      

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory



      - run: go get -v -t -d ./...
      - run: go test -race

